insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('e9991014-23cc-4429-b631-54d4dd063b7b','Karolina','karolinalondon@googlemail.com','10,000 users on the app','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1781823741744-b5234dd52a2200d9a1cb0b72/q1.webm','recordings/1781823741744-b5234dd52a2200d9a1cb0b72/q1.webm','91','NY Tech Week','[Q1] I'm going to be celebrating 10 000 members on the app everyone loving talking to a future self and being able to feel fulfilled in their life and step into their highest potential I'm very excited for everything that's to come I would know

[Q2] it was her because she would feel confident in the way she moves in the way she talks very clear in her vision and being able to express that to everyone around her She would not hesitate on her next step She would be very engaged with everyone and present with everyone and truly the future self needs

[Q3] to show up in career most being able to take very clear steps ahead without waiting too long not letting perfectionism get in the way or imposter syndrome because of everything that's moving so fast in this space we need to move fast Currently cost opportunities and

[Q4] not potentially catching them early enough Hi hi hi what would you have to stop

[Q5] believing about sorry I need to do this it's timed I would have to stop believing that things take time and that I might not have what it takes and genuinely step into this new chapter with confidence','[object Object]','2026-06-18 23:03:11.6+00','2026-06-19 00:03:11.6+00','2026-06-20 14:00:54.116022+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('8d894b6e-b9ec-415d-b6f9-4697398c30cb','Karol','karolinalondon@googlemail.com','10,000 app users','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1782762330200-403afe7cca3e72517a2e2242/q1.webm','recordings/1782762330200-403afe7cca3e72517a2e2242/q1.webm','95','NY Tech Week','[Q1] A year from today I'm celebrating 10 000 users on the app being able to raise 5 million for the company and thriving in my environment releasing my music and everything that I ever wished for coming true one by one

[Q2] She would believe by herself that anything is possible that she already won she has everything she ever wanted and needed and then some and she just needs to continue to believe in her potential as she moves about her day and about her goals Everything is possible And my career

[Q3] I want to be able to align the right people motivate them to keep winning with me I want to be able to show all of my stakeholders and partners what we're capable of and how we are already changing the industry Find opportunities I think there has

[Q4] been too much of people pleasing and imposter syndrome I think it's time to step into everything I ever dreamt of and stop doubting myself I'd have to stop believing that I might not have what it

[Q5] takes I clearly do and I need to stop showing that to people and to myself Every single day I have so much evidence that I'm so capable of everything','[object Object]','2026-06-29 19:46:35.152+00','2026-06-29 19:47:35.152+00',null,null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('346aae3f-dccd-4037-b66a-40f0248af387','Rebecca','rebecca.riggs@gmail.com','Having the courage to start pursue what I am passionate about','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780514643486-4fc0ca48753b6599f03c248a/q1.webm','recordings/1780514643486-4fc0ca48753b6599f03c248a/q1.webm','72','NY Tech Week','[Q1] So one year from today I'll be celebrating users enjoying the product that I built and it really impacting their lives

[Q2] People

[Q3] of helping others in

[Q4] their lives It has made me deviate from what I love making me a little bit sad and it has prevented me from giving back I

[Q5] would have to stop believing that it wasn't the right time or that I couldn't do it I would have to start believing I'm capable','[object Object]','2026-06-03 19:24:51.644+00','2026-06-13 19:24:51.644+00','2026-06-14 14:01:10.262766+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('19b0b811-f9da-4f28-834a-af8717e9134a','wewe','karolinalondon@googlemail.com','10,000 users','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1782762674350-360558b775e7131cf68856d9/q1.webm','recordings/1782762674350-360558b775e7131cf68856d9/q1.webm','95','NY Tech Week','[Q1] I'm going to be celebrating raising 5 million for this company launching my criticism happiness to the world and having been 2 536 000 downloads in the first two weeks of launch being able to move between LA and SF I would know it was her

[Q2] because she already moves with confidence and ease and quiet reassurance that everything she touches turns into gold I mostly need them to show up in

[Q3] my work I need them to know that everything I already have is because of me not anyone else and that I can move mountains if I truly am passionate about something My opportunities are aligned for me

[Q4] I know that they won't miss me but just being able to truly realize my full potential is my goal going forward No apologies no holding back I don't know what it takes I know that I do I just need to keep at

[Q5] it because I keep showing myself every day that I'm capable of everything I ever desired','[object Object]','2026-06-29 19:51:35.387+00','2026-06-29 19:52:35.387+00',null,null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('07bf3284-f078-4c22-80e9-13d734952202','Steven','steven.elite0106@gmail.com','AI Engineer @ Space of Mind','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780590791629-941f638968792f4a29d6f7a0/q1.webm','recordings/1780590791629-941f638968792f4a29d6f7a0/q1.webm','103','NY Tech Week','[Q2] you you

[Q4] you

[Q5] you','[object Object]','2026-06-04 16:39:04.005+00','2026-06-04 16:40:04.005+00','2026-06-04 16:40:20.715826+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('a78b5aea-b0ab-425c-b76f-8b013c836ed2','Anais','anais@amela.club','Getting more customers','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780516646965-10d51fe851718a8aeb926cb3/q1.webm','recordings/1780516646965-10d51fe851718a8aeb926cb3/q1.webm','79','NY Tech Week','[Q1] Okay I will be celebrating being profitable and having increased my membership to over 5 000 members

[Q2] She will probably be smiling like ear to ear I should probably believe that she can go through changes and she can like she can like the phoenix she is

[Q3] Where is the place I think whenever I talk to potential future customers sometimes I feel like it's a bit daring and like I have a hard time explaining what we do and how we can add value but I know we add value So I think I just need to make sure that I show up as my authentic self

[Q4] Everything like we could go belly up I think if I don't believe in the dream that I'm selling it's really hard to sell And then I don't get to build the impact that I want to leave behind this world with

[Q5] I need to stop believing that everything is linear I need to just realize that I will fucking figure it out day at a time','[object Object]','2026-06-03 19:58:27.584+00','2026-06-13 19:58:27.584+00','2026-06-14 14:01:10.465591+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('90286749-8895-42bd-a34b-596da79bfd10','kara','karolinalondon@googlemail.com','10,000 users','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1782763577882-5e734ab319853848643b6a9a/q1.webm','recordings/1782763577882-5e734ab319853848643b6a9a/q1.webm','97','NY Tech Week','[Q1] I'm celebrating raising 5 million for the company and actually being able to reach thousands if not millions of users upon launch this summer and succeeding in all of our pilots and scaling this massively to the world She

[Q2] would believe that anything is possible and that everything that she ever desired is already in her existence This is why there is no pressure She just moves like it's already done I need them to show

[Q3] up in my workplace more than anything else in my career to continue pushing forward and succeeding Okay testing a little bit more Yeah very very much ready Probably just

[Q4] the land opportunities and being able to achieve everything I want sooner but it doesn't mean that it's not possible I just have to stick to the timeline and stop hesitating because I know that all these things are possible Do you want to go I have to stop believing that things

[Q5] are not happening or that they're not happening fast enough because I know that everything's happening in separate time and space and I just need to keep on track','[object Object]','2026-06-29 20:06:39.526+00','2026-06-29 20:07:39.526+00',null,null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('9eaa19b9-e332-41fb-9e08-02e0752e1cf8','karolina@spaceofmind.com','karolinalondon@googlemail.com','10,000 users','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1782764043357-40716bf5cb0c3c7a78b92257/q1.webm','recordings/1782764043357-40716bf5cb0c3c7a78b92257/q1.webm','100','NY Tech Week','[Q1] Sorry could you say that again Oh my God What a fucking moronic system I need a bill person There we go

[Q2] This is support support support You're sorry but a system error has occurred Please try again later Thank you for calling Wow Testing

[Q3] testing testing

[Q4] I'm a digital assistant Are you calling about the business account on this line I see you're calling from your registered mobile device which helps us protect your account

[Q5] I can send you a text message with a link to a video No I want to speak to someone','[object Object]','2026-06-29 20:14:19.885+00','2026-06-29 20:15:19.885+00',null,null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('23596348-5196-4e7d-b256-5452c5b8d19a','Steven','steven.elite0106@gmail.com','AI Engineer @ Space of Mind','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780592607892-8a8d674c9706fc2449e24554/q1.webm','recordings/1780592607892-8a8d674c9706fc2449e24554/q1.webm','100','NY Tech Week','[Q1] Well how you doing today This is Tess Tess Tess Please keep talking','[object Object]','2026-06-04 17:09:38.58+00','2026-06-04 17:10:38.58+00','2026-06-04 17:10:50.168551+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('f1dfdb74-f056-474b-87dd-48c6385b0300','Nita','nsanger@ideainnovate.com','Successful company, financial security and a deep romantic relationship','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780511425694-b2899c364ec14274d4116fa2/q1.webm','recordings/1780511425694-b2899c364ec14274d4116fa2/q1.webm','87','NY Tech Week','[Q1] So I would be celebrating a very successful my business making multiple millions of dollars I would be moving from my house to another apartment in a place where I would really like to be And at the same time I would be celebrating a significant other in my life

[Q2] I would know that it was her if I would see the happiness on her face and the relaxation that would be there for having achieved what she was trying to achieve

[Q3] So the place I would need my future self to show up would be more on the personal side to make sure that she has the confidence that she can achieve everything that she wants to

[Q4] I think where staying has actually cost me has been because I keep on doubting myself and I kind of go a little bit into self pity where I'm like why is this happening to me until I step back and decide that it's actually showing me or getting me ready for the next phase of my journey

[Q5] I would the thing that I would need to stop believing in myself is like the woe is me going into the pity mode and sort of knowing that this is giving me the strength that I need to achieve the next version of myself','[object Object]','2026-06-03 18:31:37.751+00','2026-06-13 18:31:37.751+00','2026-06-14 14:01:08.597363+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('df16eefe-233a-4ba1-a4b9-34d539d6d475','Alex','allymilewich@gmail.com','Peace and support to scale the company without back to back meetings all day','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780517050954-b4c33fa25fe82252e6d0c6ea/q1.webm','recordings/1780517050954-b4c33fa25fe82252e6d0c6ea/q1.webm','98','NY Tech Week','[Q1] A year from today I will be free not relying on others financially stable and my organization will be at a place where it's grounded

[Q2] She would be walking tall she would be smiling she would not be moving too quickly she would be confident and she would just be naturally herself and not so apologetic

[Q3] I need my future self to be unapologetic and to be decisive and to be confident knowing that she's loved and accepted and brilliant as is and she can keep

[Q4] learning It's cost me my health it's actually just cost me my time I'm not peaceful and I haven't been in so long and I keep doing the same thing and expecting different results

[Q5] I have to stop believing that I'm not good enough I have to stop believing that I'm not smart enough that I'm not beautiful enough that I'm not bold enough and that I don't have all the answers because you don't need to have all the answers to make change and to be the right person','[object Object]','2026-06-03 20:06:18.002+00','2026-06-13 20:06:18.002+00','2026-06-14 14:01:10.653982+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('e3e84ea5-0e5a-4139-be2b-71c78928cb91','Kaila','kailajlim@gmail.com','Having my own public speaking coaching practice','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780518274909-626ab86461dc49fd46174384/q1.webm','recordings/1780518274909-626ab86461dc49fd46174384/q1.webm','100','NY Tech Week','[Q1] A year from now I will be celebrating my public speaking coaching business and having multiple clients I'm also going to be in love like romantically and have a partner a boyfriend who will be leading towards my engagement We're going to be living in a brownstone home in Brooklyn with just gorgeous archways detail

[Q2] and dislike We have a local community We're both social and he has a quiet power to him If that version of you walking right now how would you know it was her She would feel like she walks on air super protected She believes that everything in life works out for her She can always trust herself She knows that she has family no

[Q3] matter what The one place I most need my future self to show up is in my business It's definitely a conversation I need her to show up and how she gets ready how she treats herself sleeping enough for sure Taking care of her skin her diet cutting off any relationships that drain her and life

[Q4] What does staying where you are actually cost me Oh gosh What does staying where I am actually cost me It has cost me my future self which is probably priceless I should truly be chasing after the moment of my dreams and becoming her and I have decided to stay to what is familiar like the familiar hell like living

[Q5] in What would you have stopped believing by yourself I would have to stop believing that just because it's convenient means that I have to do it Just because I can do it just because I can handle this level of stress means that I have to do that Not true I deserve better I deserve smooth I deserve flow love light','[object Object]','2026-06-03 20:28:42.233+00','2026-06-13 20:28:42.233+00','2026-06-14 14:01:10.841969+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('4219876d-2d5f-4c4a-95fa-d849b282b1b2','Aparajita','aparajita@leftlane.com','Promoted at left lane, working in a field I'm passionate about, healthy balanced lifestyle','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780518942057-d6d729b2ced35bc796148ee0/q1.webm','recordings/1780518942057-d6d729b2ced35bc796148ee0/q1.webm','62','NY Tech Week','[Q1] I'm going to be celebrating working in a field that I'm very passionate about having succeeded at my current job at Left Lane and waking up very excited every day I will also be living a well balanced lifestyle and taking control

[Q2] She is physically fit emotionally happy and balanced She wakes up every single day very excited to go to work and is working on something she's passionate about and very good at

[Q3] I need to ask for more things I need to ask for the promotion I need to take more initiative and be louder In health I need to wake up earlier Potentially

[Q4] a promotion not feeling good about my body Stop

[Q5] believing that I need an external force to tell me to do something and that I can just choose to do something myself','[object Object]','2026-06-03 20:36:39.389+00','2026-06-13 20:36:39.389+00','2026-06-14 14:01:11.031376+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('4b9733dd-46ac-4ded-acb8-c90cf441f7c2','Nika','dominikad@gmail.com','Launch','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780512790174-8e13da2944bd5ecb92824c78/q1.webm','recordings/1780512790174-8e13da2944bd5ecb92824c78/q1.webm','93','NY Tech Week','[Q1] A year from today I'm gonna be celebrating my own company Where I could work from anywhere Live my best life travel the world

[Q2] She's powerful and how she speaks And the one wants to talk to her everyone wants to find out

[Q3] In really business in business conversations that's where I need the most help I'm a little shy when it comes to talking about myself Oh

[Q4] It's cost me everything it's costing me money future Feeling safe feeling powerful Connections That's about it

[Q5] oh I'm not good enough that I'm not smart enough the I Can't find somebody that I'm not successful I'm not lovable Yeah that needs to stop','[object Object]','2026-06-03 18:54:29.348+00','2026-06-13 18:54:29.348+00','2026-06-14 14:01:09.170629+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('86ac013b-9168-4b0b-afa8-7ee0f8a399c7','arek','arek.komarnicki@gmail.com','acasda','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780501186808-57922d549a1c683ae8b32730/q1.webm','recordings/1780501186808-57922d549a1c683ae8b32730/q1.webm','161','NY Tech Week','[Q1] This is chat input and set button that's the border radius of the rest of the app So input border radius is okay but set button needs to be round Fixed The back button is a chat conversation now let's navigate to the main chat

[Q2] The chat thread now uses the same dark top header style as the rest of the app with the back button on the left the message input UI is cleaner and longer The keyboard send key now submits the message instead of adding a new line I also check the other menus

[Q3] 30 seconds 30 seconds is too long because

[Q4] someone will say only 5 and then he will sit and stare

[Q5] Because he is screaming of agony Yeah there is a minimum duration so it's enough to change it to 15 Updating next update will be shortly','[object Object]','2026-06-03 15:43:07.694+00','2026-06-13 15:43:07.694+00','2026-06-14 14:01:07.113248+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('478d4a4b-efcc-4288-9377-dc17d55789a4','Iajaja','hsja@gmail.com','Wcscec','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780501150073-33de08c85c242cb7bf447410/q1.webm','recordings/1780501150073-33de08c85c242cb7bf447410/q1.webm','154','NY Tech Week','[Q1] Tak co będę dzisiaj świętować Będę świętować sukcesywny wydarzenie piękny wynik tyle ludzi tyle ekscytacji Jestem naprawdę bardzo szczęśliwa za wszystko co zdobyliśmy Moja przyszła osoba będzie bardzo bardzo wdzięczna Dziękuję Aro ci naprawdę za pomoc Też dziękuję

[Q2] Dziękuję

[Q3] Dziękuję Moja przyszła osoba będzie bardzo wdzięczna za wszystko co zdobyliśmy Jestem bardzo wdzięczna za wszystkie zmiany za wszystkie wspaniałe rzeczy które udało nam się zdobyć Jestem naprawdę naprawdę szczęśliwa za wszystko co do nas przychodzi Dziękuję Co jeszcze nie zrobiłam to prawdopodobnie tylko finansowanie

[Q4] oportunitały i możliwość podjęcia przysięgi bez względu na wszystko To jest naprawdę to na co chcę skupić się następnie 30 sekund to za długo Nie da się skorzystać tylko

[Q5] będzie się ciągnąć Muszę przestać wierzyć Muszę przestać wierzyć że może nie mam tego co potrzeba To jest tylko wierzę i moja przyszła osoba już o tym wie A nie ma Ara możliwości skrócić tego 10 15 sekund','[object Object]','2026-06-03 15:43:58.399+00','2026-06-13 15:43:58.399+00','2026-06-14 14:01:07.482575+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('a19766ab-b2b4-44ed-8561-97370d15e848','Kara','kara@gmail.com','Dd','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780504258545-8238fc904e42eca65682397b/q1.webm','recordings/1780504258545-8238fc904e42eca65682397b/q1.webm','83','NY Tech Week','[Q1] Everyone today I'm celebrating becoming already a version of me who is so excited and can't wait for what's to come I am genuinely so ecstatic about everything That's why I said you should have tested it once because that's what it was like Yeah But then if

[Q2] that version of you walked into the room right now how would you know her I she's bright shining like a star She knows everything there is to know about life and there's no hesitations for what's to come We can just tell them like the mic is extra but you can just speak directly We just tell them because the question no they're

[Q3] not meant to they're just reading it Well most features show up in your business Okay so I actually One place in you've just shop is in my career just making sure I kick ass every single day It has probably

[Q4] cost me time I think times everything and we want to make sure that we give people time To be able to achieve all their dreams because time is so precious and we don't want to waste it I would have

[Q5] to stop believing that things might not be what they that things are hard or that they're There's not enough time There's not enough opportunity because there's always enough for all of us','[object Object]','2026-06-03 16:31:24.995+00','2026-06-13 16:31:24.995+00','2026-06-14 14:01:07.854413+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('87cf49be-3690-47a7-8bad-7cd6ab9f775a','Stephanie','stephanie@immersiveriggs.com','Ferraris in hawaii','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780505493060-cab452407e02950bf4d59e97/q1.webm','recordings/1780505493060-cab452407e02950bf4d59e97/q1.webm','86','NY Tech Week','[Q1] Hi a year from today I am going to be celebrating my financial freedom my family's good health and my connection to life

[Q2] I walked into a room right now Oh she would love her They would high five each other have a great time and she believes she can just be without having to try too hard

[Q3] I need my future self to show up in the small moments in the moments before in the quiet in the moment before you get to take action to be present

[Q4] It's cost me time it's cost me energy it's cost me happiness and brought sadness but I've been actively working against it so let's go

[Q5] I would have to stop believing that I'm less than other people I would have to stop believing that I had to show up the way that other people do and just be myself','[object Object]','2026-06-03 16:51:59.649+00','2026-06-13 16:51:59.649+00','2026-06-14 14:01:07.996587+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('37984d0d-f5b5-4904-99fc-ae64a73ea60f','Snigdha','snigdhg@uci.edu','Patented new product','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780506302667-a8f87bfbc4761d6c39106738/q1.webm','recordings/1780506302667-a8f87bfbc4761d6c39106738/q1.webm','143','NY Tech Week','[Q1] A year from now I probably would be celebrating my patented product which is a new product that I will be developing and looking for success and this product is going to solve a real niche need but for impact and definitely a novelty of bringing something new into the world

[Q2] If that version of me walked into a room right now how would you know it was her She's going to walk with a lot of confidence with a lot of impact with a lot of humility at the same time pride that she was able to do something for the world that didn't exist up until now and create a product that is actually changing life through technology in a way that was not possible before

[Q3] Where is one place you most need your future self to show up in your business in a conversation I think one place where I need my future self to show up is the past version of me where go get attitude a sales that you're ready to make and finding the real need to make that impact and sell a product So I think from a business standpoint a good salesmanship is something that I want my future self to show up with

[Q4] Staying where you are has actually costed me an opportunity of risk but this has also come because of a lot of risk taking and lessons learned previously And probably it's been amazing in the sense that I've been moving and a more cautious self but I think the free spirited to get back up this question is now probing me to get back that risk levels in some ways

[Q5] What would you have to stop believing about yourself for the next version to be possible That the crazy ambitious free spirited driven girl is actually more fun than a cautious lessons learned risk girl So I guess you know go back to being the carefree version of you','[object Object]','2026-06-03 17:05:39.647+00','2026-06-13 17:05:39.647+00','2026-06-14 14:01:08.116507+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('9d3e5724-6bb1-4179-86e0-12aac6e7e5e6','Ore','orese@base44.com','Raise and more family time','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780520459548-167685491fb3692c24f91d4a/q1.webm','recordings/1780520459548-167685491fb3692c24f91d4a/q1.webm','100','NY Tech Week','[Q1] Hopefully I'll be celebrating my year and a half at Base 44 My parents retirement hopefully so they could spend more time doing the things they love and celebrating my health both mental and physical That's the goal I would

[Q2] know because confidence a lot more mature than I currently am Probably believes that you can take over the world more than I do now

[Q3] I need my future self to make some money I also need my future self to be more patient and I need my future self to spend more time with family and not just prioritize work

[Q4] I don't think I've really stayed where I am I've always been moving around I always want to do the next thing Ever since I was a kid I always said I was bored if we weren't doing anything so really just moving around constantly so that's positive

[Q5] I don't know honestly You have to stop believing about yourself for the next version to be possible When you just stop believing that because of my age I can't do certain things which is just not true','[object Object]','2026-06-03 21:02:48.221+00','2026-06-13 21:02:48.221+00','2026-06-14 14:01:11.500963+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('eb4a2e5b-d24e-4bb9-a8df-b3c22298bead','Artisha','artisha@artishawalker.com','100k months','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780520996519-de0d12bf008fcf6033374488/q1.webm','recordings/1780520996519-de0d12bf008fcf6033374488/q1.webm','100','NY Tech Week','[Q1] What are you going to be celebrating a year from now A year from now I would love to be celebrating my first 100K month that I've made in business I feel like I have a lot of traction and momentum that has been building and compounding on itself right now And so I'm really pumped for what this next stage will

[Q2] be How would you know it was her She would be super confident in the way she speaks and shows up and dresses and interacts with people She would know her message so clearly in a way that makes people lean in and listen And she would believe that she is really the one to be leading the conversation

[Q3] One place I would need my future self to show up In your business in a conversation in an ask you haven't made yet I mean I think there's a piece of me that actually needs to lean into being a bit more entitled I think I'm very humble in a sense but if I were to take up more space and expect more from others I would be getting results quicker And so that's something I need to focus on

[Q4] Staying where I am has cost me I would say revenue And being where I truly feel like in my mind that I'm meant to be that keeps me a little stuck and stagnant But it's really costing me stepping into the version of myself that I see for sure I

[Q5] would have to stop believing that massive results need to take a ton of time And that's something that I've already shed as a limiting belief But even more so I think I really need to tap into and understand that life can change in an instant And truly believe that and I do But I think there's a deeper integration and embodiment of what that even means of believing something is possible for me','[object Object]','2026-06-03 21:14:38.507+00','2026-06-13 21:14:38.507+00','2026-06-14 14:01:11.658634+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('b494f9da-88a0-426b-a8bb-d22c0d5d7677','Lauren','laurentayloewilson@gmail.com','Money abundant','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780521551227-8c87c8d33412369f7381a51c/q1.webm','recordings/1780521551227-8c87c8d33412369f7381a51c/q1.webm','100','NY Tech Week','[Q1] Okay is this working I think it is What are you going to be celebrating a year from today A year from today is summer 2027 I think I'm going to be celebrating that I feel financial freedom I'm on this journey to you know it's really reckless with money and money

[Q2] How would you know it was her I would know it was her because the energy is calm What does she believe about herself that you don't quite yet That she can build her own security

[Q3] Where is one place you most need your future self to show up In business In business and for a future partner So I feel like that the type of person I want we are on equal footing

[Q4] I think it has cost me like some freedom really And so I'm excited for that not to be the case

[Q5] I think I would have to stop believing that I can't make the changes necessary or that what I buy or where I go or what I'm seen at or with is a defining thing about me And that sometimes acquires','[object Object]','2026-06-03 21:21:20.577+00','2026-06-13 21:21:20.577+00','2026-06-14 14:01:11.931888+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('3f1c862b-7335-4297-9f7c-370baf0bb338','Vera','vera@globalelementsconsulting.com','Next chapter','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780521979679-0ad5867dc5b9c0bae0885654/q1.webm','recordings/1780521979679-0ad5867dc5b9c0bae0885654/q1.webm','100','NY Tech Week','[Q1] I am celebrating a year from today my 50th birthday and the fact that I broke through whatever ceilings or limitations that I have imposed on myself and I am completely and utterly free to do and play in any way that I did

[Q2] The version of me that I recognize is powerful she's free she exudes energy and what I don't quite believe in myself is that I am her yet

[Q3] I need my future self to show up in my presence in my being and in the certainty that everything is already working out just the way that it is meant to be and not to take any deviations as setbacks but accept that they're part of the journey

[Q4] It cost me the progress it cost me time and it cost me the confidence in what I'm doing I was lost for a very long time and now

[Q5] I'm free I have to stop believing that I have limits and that things are hard because they're not and I have to start believing that I am following a divine path and it's not a singular path and everything's','[object Object]','2026-06-03 21:28:25.504+00','2026-06-13 21:28:25.504+00','2026-06-14 14:01:12.309659+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('38a2782a-b8d4-4318-85e0-5c3069092f05','Batool','batoolfrizvi@gmail.com','Making more money','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780522676349-943b6c2c8e20f38f5f271a7d/q1.webm','recordings/1780522676349-943b6c2c8e20f38f5f271a7d/q1.webm','100','NY Tech Week','[Q1] What are you going to celebrate a year from today I will be celebrating a practice that is a lot more organized a new brand a new website I'm going through a rebrand right now and a year from now my rebranding will be completed

[Q2] If that version of you walked into a room right now how would you know it was her What does she believe about herself And you don't quite believe it That girl is very confident She walks into a room confident like she belongs She is not afraid of visibility

[Q3] She wears the one place you most need your future self to show up I need my future self to show up and taking care of her health and doing what she plans on doing managing her time going to bed early waking up early

[Q4] staying where I am has cost me financially and health wise and in my relationships I believe I believe I would have been a happier person if I had accomplished the goals that I

[Q5] had I would have to stop my limiting beliefs I would have to stop believing that I'm not the smartest person in the room or other people know things more than I do or that what I have to say is not important enough','[object Object]','2026-06-03 21:40:16.318+00','2026-06-13 21:40:16.318+00','2026-06-14 14:01:12.509739+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('776b2ece-da0a-43b2-ac06-2192e506b488','Kamila','kamila@kamilahoe.com','Build my aligned community of partners throughout the creative, finance, tech, and media industries. Make my first million.','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780523980873-7f70435a40a52865fff719a2/q1.webm','recordings/1780523980873-7f70435a40a52865fff719a2/q1.webm','100','NY Tech Week','[Q1] A year from now I'm going to be celebrating making my first million dollars I'm going to be celebrating having multiple aligned communities of people

[Q2] If that version of me walked into a room right now I would know it's her because she would just be so calm she would be so confident she would have a lot of fun and I think that she would completely own her power and know that anything is possible truly by execution

[Q3] Um I think I just need to properly sell my services more quickly and to my ideal audience that I've been avoiding

[Q4] The cost of staying is being where I am having a lot of opportunity having multiple focuses but not properly scaling the way that I really want and it has cost me a lot of peace as well

[Q5] that I need more I need to stop believing that I need more I need to be better that I need more resources and yeah I need to stop believing that it's going to happen tomorrow when my situation is different because it's going to happen now and in this current environment','[object Object]','2026-06-03 22:01:38.341+00','2026-06-13 22:01:38.341+00','2026-06-14 14:01:12.865084+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('9d6e8b5a-1cf2-4340-94b3-394febb2fdd7','Shah','shah@gmail.com','Shah','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780510942417-a7afbdf9891c08d87fb71599/q1.webm','recordings/1780510942417-a7afbdf9891c08d87fb71599/q1.webm','100','NY Tech Week','[Q1] Okay testing testing testing testing testing testing and understanding 20 seconds All right

[Q2] All right We can talk about it You know the conversations that we've been having Believe about yourself Don't quite believe that yet 20 seconds One take And we're going to try and see if this 20 second limit is up

[Q3] and just kind of yes just right after Yes just kind of We did go through We did Yeah The Wi Fi Yeah So we just limited Yeah Yeah But we just limited the minutes to 20 seconds

[Q4] So Did you say that Yeah But you know like how we had the limit to 30 seconds It wouldn't stop No I told you we have to limit it to a few seconds I don't know Because it wouldn't stop The button It wouldn't press It would say please keep talking It was shorter than that Oh So did they change that Yeah You just changed

[Q5] it And you should actually come back Because the reason is because Yes Believe I do believe This is the next version if you saw And it's possible And we're going to do this Keep it going Keep it going Yeah I hope it's able to capture all the analysis','[object Object]','2026-06-03 18:24:19.867+00','2026-06-13 18:24:19.867+00','2026-06-14 14:01:08.417801+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('e41a1688-c846-4779-8021-b091139c9dee','Mary','mary@lasthurrah.com','Raising enough to scale and launch','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780514121645-7f4ebadb8eeb289399ad5852/q1.webm','recordings/1780514121645-7f4ebadb8eeb289399ad5852/q1.webm','100','NY Tech Week','[Q1] A year from today I am going to be celebrating the launch and the growth and the scale of my amazing company that I have started with my dad and I'm hoping that

[Q2] I would know it was her because she'd be extremely confident and she would be believing in herself that she did it and could do it and can do anything because she's already done it I think I worry

[Q3] I think it needs to show up mainly in my business and show me how to be as confident about what I'm doing that I am not right now and to have less fear

[Q4] Staying where I am is costing me anxiety it's causing me anxiety and it would cost me

[Q5] I have to stop believing that I am not worthy I can do this That's what I need to be telling myself and that I am the person to be doing this I believe it but sometimes I get stuck','[object Object]','2026-06-03 19:16:59.374+00','2026-06-13 19:16:59.374+00','2026-06-14 14:01:10.064918+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('d70a92c1-a49f-4133-9e54-cac97d1362da','Kristen','kriscast9@gmail.com','Growing my nonprofit and my personal wealth','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780512363484-0ebcc4df073c03bbb16728db/q1.webm','recordings/1780512363484-0ebcc4df073c03bbb16728db/q1.webm','100','NY Tech Week','[Q1] Hi so a year from now I'm going to be celebrating how CAFE my nonprofit organization is really known throughout the U S even more so and how we're making such a bigger impact and are getting more sustainable funding where we're making this movement toward entry

[Q2] and also building my brand So really celebrating how you know I'm actually more on TV now and podcasts and really spreading this movement I would know because she'd be wearing the signature color blue that I

[Q3] always wear Oh we're in question three I think just in balance in my life I need her to show up and like how do I make it all happen I love networking and I'm really good at building my community my organization all the relationships And how does she balance that and really feel like

[Q4] yeah I mean I've built something really big but it could be so much bigger How do I visualize and like imagine where it could go and actually like execute that I'm really interested in like the new technologies and the future of like everything happening in the world now And how do I get in the forefront of that But also balance that with like

[Q5] I always believe that there's unlimited possibilities and I can make everything happen I think I have to stop believing that I have I don't know like it's hard with the limited energy So like how do I have more energy and balance and time for both my daughter and to be able','[object Object]','2026-06-03 18:48:55.394+00','2026-06-13 18:48:55.394+00','2026-06-15 13:53:40.327342+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('a6856a76-11db-4bc4-8127-0450d6ec6ee6','Kara','kara@gmail.com','Fundraise','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780501591535-120efa530d46fbcc3311ec3a/q1.webm','recordings/1780501591535-120efa530d46fbcc3311ec3a/q1.webm','80','NY Tech Week','[Q1] I'm testing testing testing testing yay Sorry I had to debug the app because the Wi Fi wasn't rendering the response Two minutes two minutes What are you going to be celebrating a year from today Blah blah blah blah blah We're going to be

[Q2] celebrating If that version of you walked into a room right now what would it do It would be so proud That version of me is already walking like they made it So happy Yes I cannot proceed

[Q3] If you just have to show up in career continued progress and genuine ability to move through fear and obstacles without any hesitations I'm super happy

[Q4] It cost me just a few minutes and time just making sure that I have enough time to achieve everything I've ever dreamed of And take no for not take no for an answer That's my goal

[Q5] I just have to stop believing I just have to stop believing that things are not possible because I know they are It's just the truth I'm just so happy that my future self is already reaching me','[object Object]','2026-06-03 15:46:53.883+00','2026-06-13 15:46:53.883+00','2026-06-14 14:01:07.7133+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('449361ca-af4e-418c-ac5f-4a51a00dab80','Nora','noramosman@gmail.com','Norvana llc','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780513104790-b922dfcf369ffe2395faca35/q1.webm','recordings/1780513104790-b922dfcf369ffe2395faca35/q1.webm','100','NY Tech Week','[Q1] What are you going to be celebrating a year from today Well considering I just launched my book Zero to Hero in March I'm going to be celebrating the success of this book the fact that I have achieved recognition for this transformative stand

[Q2] Also a lot of speaking engagements and beautiful things If that version of you walked into a room right now how would you know it was her What does she believe about herself that you don't quite believe yet Well she now knows that what she is presenting to the

[Q3] world I need to be more in my corner and less in my head I need to be more assertive in asking for what I

[Q4] want Grander opportunities bigger options for an expanded business outcomes

[Q5] That what I know now is everything I need to know There's so much more for me to know and there is an infinite amount of possibilities in how I reinvent myself It's still unwritten and my creativity is my superpower','[object Object]','2026-06-03 19:00:05.906+00','2026-06-13 19:00:05.906+00','2026-06-14 14:01:09.369323+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('664de6d1-546f-4a1e-b9f1-30da0b8534e9','Iajaja','hsja@gmail.com','Wcscec','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780501154728-3e92c756c20f5086e715f89c/q1.webm','recordings/1780501154728-3e92c756c20f5086e715f89c/q1.webm','154','NY Tech Week','[Q1] Tak co będę dzisiaj świętować Będę świętować sukcesywny wydarzenie piękny wynik tyle ludzi tyle ekscytacji Jestem naprawdę bardzo szczęśliwa za wszystko co zdobyliśmy Moja przyszła osoba będzie bardzo bardzo wdzięczna Dziękuję Aro ci naprawdę za pomoc Też dziękuję

[Q2] Dziękuję

[Q3] Dziękuję Moja przyszła osoba będzie bardzo wdzięczna za wszystko co zdobyliśmy Jestem bardzo wdzięczna za wszystkie zmiany za wszystkie wspaniałe rzeczy które udało nam się zdobyć Jestem naprawdę naprawdę szczęśliwa za wszystko co do nas przychodzi Dziękuję Co jeszcze nie zrobiłam to prawdopodobnie tylko finansowanie

[Q4] oportunitały i możliwość podjęcia przysięgi bez względu na wszystko To jest naprawdę to na co chcę skupić się następnie 30 sekund to za długo Nie da się skorzystać tylko

[Q5] będzie się ciągnąć Muszę przestać wierzyć Muszę przestać wierzyć że może nie mam tego co potrzeba To jest tylko wierzę i moja przyszła osoba już o tym wie A nie ma Ara możliwości skrócić tego 10 15 sekund','[object Object]','2026-06-03 15:42:47.178+00','2026-06-13 15:42:47.178+00','2026-06-14 14:01:06.923828+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('905d9688-9604-4e9f-8ca1-d6c17a8d9dd6','Vera','vera@globalelementsconsulting.com','Next chapter','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780521937187-4b67e6bdf752d2a34b0bbb95/q1.webm','recordings/1780521937187-4b67e6bdf752d2a34b0bbb95/q1.webm','100','NY Tech Week','[Q1] I am celebrating a year from today my 50th birthday and the fact that I broke through whatever ceilings or limitations that I have imposed on myself and I am completely and utterly free to do and play in any way that I did

[Q2] The version of me that I recognize is powerful she's free she exudes energy and what I don't quite believe in myself is that I am her yet

[Q3] I need my future self to show up in my presence in my being and in the certainty that everything is already working out just the way that it is meant to be and not to take any deviations as setbacks but accept that they're part of the journey

[Q4] It cost me the progress it cost me time and it cost me the confidence in what I'm doing I was lost for a very long time and now

[Q5] I'm free I have to stop believing that I have limits and that things are hard because they're not and I have to start believing that I am following a divine path and it's not a singular path and everything's','[object Object]','2026-06-03 21:27:38.493+00','2026-06-13 21:27:38.493+00','2026-06-14 14:01:12.099534+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('9fe878cd-ad29-469c-bedd-aa9409df8f11','Victoria','victoriaarmoyan@gmail.com','Quiet luxury','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780526991511-4e7d79781dd2363687098c95/q1.webm','recordings/1780526991511-4e7d79781dd2363687098c95/q1.webm','100','NY Tech Week','[Q1] a year from today I'm gonna be known in some capacity whether it's as like a quiet luxury figurehead somebody but somebody that's not super out there putting herself out there not like another influencer but like a Carolyn Bessette meets Alex Earl if

[Q2] that were she would be very well dressed she would be very magnetic but not demanding attention from anyone like she'd be have a gravitational pull to everybody in the room and everybody would want to just approach her

[Q3] she needs to put herself out there more in the right rooms she needs to figure out what the right rooms are and she needs to go and just again make herself known by communicating what she wants but not asking for anything I

[Q4] think a lot of stagnancy and feeling like there's no purpose and I think yeah just a lot of stagnancy and just feeling like I'm meant for something so much more and I'm meant to be you know somebody that speaks in front of crowds that's well known but

[Q5] is it that this is an oversaturated space that doesn't need somebody else and that like I'm just as interesting and cool as an Alex Earl and I will have just as many eyes on me as her and that like people want to know me just as much as they would want to know her','[object Object]','2026-06-03 22:52:44.621+00','2026-06-13 22:52:44.621+00','2026-06-14 14:01:13.039214+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('b37fe66c-bba6-4142-be80-3c599c61c6b9','Caryn','caryn@baxteradvisorsgroup.com','I am actively engaged with clients and I am speaking at events once a quarter','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780511938185-01ab670a6d7835afc15d7c6b/q1.webm','recordings/1780511938185-01ab670a6d7835afc15d7c6b/q1.webm','85','NY Tech Week','[Q1] A year from today I'll be celebrating the continued success of my new business Baxter Advisors I will have actively been engaging with two to three clients on an ongoing basis at any given time And I will have taken

[Q2] She would look more confident and give off a more

[Q3] I need to show up with meeting more private equity operating partners and direct connections that will really make an impact in what I am doing

[Q4] It has cost me the ability to move forward and have more professional and personal success

[Q5] I just have an obstacle in my way of taking my networking to the next step and I have to believe that these other private equity operating partners and people like them want my business and believe in what I'm doing','[object Object]','2026-06-03 18:39:51.499+00','2026-06-13 18:39:51.499+00','2026-06-14 14:01:08.824952+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('d7bd3ef1-4951-4ece-bb85-6084ba08c03c','Carinę','carinedemeyere@icloud.com','Women of the world','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780513529916-9c7de1f028b1679168d0088c/q1.webm','recordings/1780513529916-9c7de1f028b1679168d0088c/q1.webm','100','NY Tech Week','[Q1] What are you going to be celebrating a year from today A year from today I'm going to be celebrating that Women of the World will be having its 15th anniversary 15th 16th anniversary And we will have been traveling to China which will be a great trip

[Q2] What would you like to say to the world That I'm a true Woman of the World that I can literally go and walk into any room I'm always colorfully dressed and that people will look at me and they will feel that I radiate positive energy

[Q3] What would you like to say to the world I need to dare to ask more for money I need to know what my worth is my self worth is I want to invest but I want to invest with vision and I want to invest with a clear exit strategy I need to be more confident with

[Q4] myself It has actually cost me a lot of money I think I didn't have enough self confidence I think I stayed in a marriage Also I wanted someone else to take care of me And I think right now it's really important that I go and stand in my own strength and also move and live in the places where that's the best

[Q5] I need to stop believing that I'm not good enough that I'm not bad that I'm not the best version of myself I need to know that I'm beautiful I need to know that I'm very intelligent and I'm able to really connect the dots And I need to know that I can really build a company by myself and sell it for what it's worth','[object Object]','2026-06-03 19:08:46.82+00','2026-06-13 19:08:46.82+00','2026-06-14 14:01:09.856412+00',null,null,null);
insert into `sessions`(`id`,`first_name`,`email`,`focus`,`prompt`,`audio_url`,`audio_pathname`,`duration_seconds`,`event_name`,`transcript`,`signal_data`,`recorded_at`,`deliver_at`,`delivered_at`,`resend_email_id`,`delivery_status`,`delivery_updated_at`) values('35e1ea81-7bbd-4a3b-8336-8c45daf15dc7','Monica','monica@littleswaps.com','Little swaps , raised 1 million, I'm 10 states, 10000 businesses and 500k revenue','[{"index":1,"label":"Celebrating","text":"What are you going to be celebrating a year from today?"},{"index":2,"label":"If she walked in","text":"If that version of you walked into a room right now — how would you know it was her? What does she believe about herself that you don't quite believe yet?"},{"index":3,"label":"Where she shows up","text":"Where is the one place you most need your future self to show up? In your business. In a conversation. In the ask you haven't made yet."},{"index":4,"label":"The cost","text":"What has staying where you are actually cost you?"},{"index":5,"label":"What you'd shed","text":"What would you have to stop believing about yourself for the next version to be possible?"}]','https://unimfsraqelbdya8.private.blob.vercel-storage.com/recordings/1780519317364-21c9454e30bf6e55ac2fd164/q1.webm','recordings/1780519317364-21c9454e30bf6e55ac2fd164/q1.webm','93','NY Tech Week','[Q1] I am celebrating having raised money from a VC capital for my company 1 million yeah 1 million as a free seat

[Q2] She would believe that she deserves to be in the room that she is capable of scaling the company even to 10 million in the next two years

[Q3] I think I need to show up for my teammates and my co founders sometime I could be dismissive and sound like an appreciative it's just like a very direct style conversation and I want to make sure that I can work

[Q4] It has to stay it has growing as an entrepreneur like I think in my job corporate job and I haven't taken the leap yet because I'm scared to not being able to provide for my family

[Q5] that I cannot do it I want to believe that if I start a business and I dedicate myself 100  that I would get the revenue and the growth that I need for my company to sustain my family','[object Object]','2026-06-03 20:43:30.771+00','2026-06-13 20:43:30.771+00','2026-06-14 14:01:11.268654+00',null,null,null);
